"""Render the cross-engine observation tables in README.md from results/.

    uv run python -m adapters.report           # rewrite the README section
    uv run python -m adapters.report --check   # exit 1 if it is stale

The section is generated, never hand-written. It shows only the transitions
where adapters or modes disagree, phrased as observations and pinned to the
adapter versions, the corpus version and the corpus revision.

Schemas are compared by column name and corpus type, ignoring column order
and nullability (DuckDB and Polars record none, so `not null` inside nested
types is dropped too). A type with no corpus equivalent compares by the
engine's native spelling.

Engines spell the same file differently (a dictionary column is `VARCHAR` in
DuckDB and `Categorical` in Polars), so a combined read is not compared
across engines directly. It is classified against the same engine's reads of
each version alone: read like `from`, like `to`, like both (when the engine
reads both versions alike), like neither, or an error. A transition is a
disagreement when these classes, or the row counts, differ between adapters
or modes. Single-version reads are compared across engines directly, in a
table of their own.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from tabular_evolution.generate import MANIFEST
from tabular_evolution.validate import load_json, scenario_dirs

from .base import OPERATIONS
from .runner import RESULTS_DIR, read_results

README = Path("README.md")
BEGIN = "<!-- observations:begin (generated by `python -m adapters.report`; do not edit) -->"
END = "<!-- observations:end -->"
ENGINE_NAMES = {"duckdb": "DuckDB", "polars": "Polars", "pyarrow_dataset": "PyArrow"}

Key = tuple[str, str, str]  # scenario_id, from, to


def latest_results(root: Path) -> Path | None:
    versions = [d for d in (root / RESULTS_DIR).glob("*") if d.is_dir() and re.fullmatch(r"\d+\.\d+\.\d+", d.name)]
    return max(versions, key=lambda d: tuple(map(int, d.name.split(".")))) if versions else None


def _schema_key(record: dict[str, Any]) -> tuple[tuple[str, str], ...]:
    return tuple(
        sorted(
            (f["name"], f["type"].replace(" not null", "") if f["type"] else f"native:{f['native_type']}")
            for f in record["result_schema"]
        )
    )


def _signature(record: dict[str, Any]) -> Any:
    return "error" if record["status"] == "error" else (record["row_count"], _schema_key(record))


def _relative(record: dict[str, Any], alone: dict[str, dict[str, Any]]) -> str:
    """How a combined read relates to the same engine's reads of each version."""
    if record["status"] == "error":
        return "error"
    from_, to = record["inputs"]
    key = _schema_key(record)
    like = [v for v in (from_, to) if alone[v]["status"] == "success" and _schema_key(alone[v]) == key]
    if not like:
        return "neither"
    return like[0] if len(like) == 1 else "both"


def _focus(transition: dict[str, Any]) -> list[str]:
    """Top-level columns a transition touches, in first-mention order."""
    paths = [m["path"] for m in transition["mutations"]] + [m["old_path"] for m in transition["mutations"] if "old_path" in m]
    paths += [c["path"] for c in transition["invariants"]["value_changes"]]
    tops = [re.split(r"[.\[]", p, maxsplit=1)[0] for p in paths if p]
    return list(dict.fromkeys(tops))


def _types(record: dict[str, Any], columns: list[str]) -> str:
    present = {f["name"]: f["native_type"] for f in record["result_schema"]}
    parts = [f"`{present[c]}`" if c in present else "(absent)" for c in columns]
    if len(columns) == 1:
        return parts[0]
    return "; ".join(f"{c}: {p}" for c, p in zip(columns, parts))


def _cell(record: dict[str, Any], columns: list[str], rows: int, relation: str = "both") -> str:
    if record["status"] == "error":
        return f"error: `{record['error_class'].rsplit('.', 1)[-1]}`"
    cell = _types(record, columns)
    if relation != "both":
        cell += f" *{relation}*"
    if record["row_count"] != rows:
        cell += f", {record['row_count']} rows"
    return cell


def _columns_of_disagreement(records: list[dict[str, Any]]) -> list[str]:
    """For a transition with no declared change: the columns whose type differs."""
    seen: dict[str, set[str]] = defaultdict(set)
    successes = [r for r in records if r["status"] == "success"]
    for r in successes:
        for name, type_ in _signature(r)[1]:
            seen[name].add(type_)
    names = {f["name"] for r in successes for f in r["result_schema"]}
    return sorted(n for n in names if len(seen[n]) > 1 or any(n not in {f["name"] for f in r["result_schema"]} for r in successes))


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    def line(cells: list[str]) -> str:
        return "| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |"

    return [line(header), line(["---"] * len(header)), *(line(r) for r in rows)]


def render(root: Path, results_dir: Path) -> str:
    by_adapter = {p.stem: read_results(p) for p in sorted(results_dir.glob("*.jsonl"))}
    records = [r for rs in by_adapter.values() for r in rs]
    manifests = {m["scenario_id"]: m for m in (load_json(d / MANIFEST) for d in scenario_dirs(root / "fixtures"))}
    versions = sorted({(r["adapter"], r["adapter_version"]) for r in records})
    corpus = sorted({(r["corpus_version"], r["corpus_revision"]) for r in records})
    platforms = ", ".join(sorted({r["platform"] for r in records}))
    modes = {
        op: [(a, m) for a, rs in by_adapter.items() for m in dict.fromkeys(r["mode"] for r in rs if r["operation"] == op)]
        for op in OPERATIONS
    }
    grouped: dict[Key, dict[tuple[str, str, str], list[dict[str, Any]]]] = defaultdict(lambda: defaultdict(list))
    for r in records:
        grouped[(r["scenario_id"], r["from"], r["to"])][(r["operation"], r["adapter"], r["mode"])].append(r)

    def transition(key: Key) -> dict[str, Any]:
        return next(t for t in manifests[key[0]]["transitions"] if (t["from"], t["to"]) == key[1:])

    def row_count(sid: str, version_id: str) -> int:
        return next(v["row_count"] for v in manifests[sid]["versions"] if v["id"] == version_id)

    together_rows, each_rows, agreeing = [], [], []
    for key in sorted(grouped):
        sid, from_, to = key
        cells = grouped[key]
        label = f"`{sid}` {from_}→{to}"

        outcomes = [cells[("read_versions_together", a, m)][0] for a, m in modes["read_versions_together"]]
        alone = {
            a: {r["inputs"][0]: r for r in cells[("read_each_version", a, m)]} for a, m in modes["read_each_version"]
        }
        relations = [_relative(r, alone[r["adapter"]]) for r in outcomes]
        rows = row_count(sid, from_) + row_count(sid, to)
        if len({(rel, r["row_count"]) for rel, r in zip(relations, outcomes)}) > 1:
            focus = _focus(transition(key)) or _columns_of_disagreement(outcomes)
            together_rows.append([label, *(_cell(r, focus, rows, rel) for r, rel in zip(outcomes, relations))])
        else:
            agreeing.append(label)

        pairs = [cells[("read_each_version", a, m)] for a, m in modes["read_each_version"]]
        if len({tuple(_signature(r) for r in pair) for pair in pairs}) > 1:
            focus = _focus(transition(key)) or _columns_of_disagreement([r for pair in pairs for r in pair])
            each_rows.append(
                [label, *(" → ".join(_cell(r, focus, row_count(sid, r["inputs"][0])) for r in pair) for pair in pairs)]
            )

    total = len(grouped)
    version = corpus[0][0] if len({c[0] for c in corpus}) == 1 else ", ".join(sorted({c[0] for c in corpus}))
    revisions = ", ".join(f"`{rev[:12]}`" for _, rev in corpus)
    engines = ", ".join(f"{ENGINE_NAMES.get(a, a)} {v}" for a, v in versions)
    links = ", ".join(f"[`{p.name}`]({p.relative_to(root).as_posix()})" for p in sorted(results_dir.glob("*.jsonl")))
    out = [
        BEGIN,
        "",
        f"Corpus {version} at revision {revisions}; {engines}; recorded on {platforms}. Full records: {links}.",
        "",
        f"**Reading two versions as one dataset.** Adapters or modes disagree on "
        f"{len(together_rows)} of {total} transitions. Each cell shows the result type of the columns the "
        "transition touches, in the engine's own spelling, or the class of the error the engine raised. "
        "A version in italics (*v0*): the whole result has the schema the same engine reads from that "
        "version alone; "
        "*neither*: it matches neither (a promoted type, or columns from both); no mark: the engine reads "
        "both versions alike and the result matches them. A row count is shown when it is not the sum of "
        "both versions.",
        "",
        *_table(["transition", *(f"{ENGINE_NAMES.get(a, a)} `{m}`" for a, m in modes["read_versions_together"])], together_rows),
        "",
        f"Every adapter and mode reads the other {len(agreeing)} alike: {', '.join(agreeing) or '-'}.",
        "",
        f"**Reading each version on its own** (`from` → `to`). Adapters disagree on {len(each_rows)} of "
        f"{total} transitions; here the differences are in how each engine represents a single file.",
        "",
        *_table(["transition", *(ENGINE_NAMES.get(a, a) for a, _ in modes["read_each_version"])], each_rows),
        "",
        END,
    ]
    return "\n".join(out)


def replace_section(text: str, section: str) -> str:
    start, end = text.index(BEGIN), text.index(END) + len(END)
    return text[:start] + section + text[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m adapters.report", description=__doc__.split("\n\n")[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="exit 1 if README.md is not current")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    results_dir = latest_results(root)
    if results_dir is None:
        print(f"no results under {RESULTS_DIR.as_posix()}/", file=sys.stderr)
        return 2
    readme = root / README
    text = readme.read_bytes().decode("utf-8")
    updated = replace_section(text, render(root, results_dir))
    if args.check:
        if updated != text:
            print("README.md observation tables are stale; run python -m adapters.report", file=sys.stderr)
            return 1
        return 0
    readme.write_bytes(updated.encode("utf-8"))
    print(f"README.md: observation tables from {results_dir.relative_to(root).as_posix()}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
